const flightListDataFormat = [
    {
       "type":"flight-offer",
       "id":"1",
       "source":"GDS",
       "instantTicketingRequired":false,
       "nonHomogeneous":false,
       "oneWay":false,
       "lastTicketingDate":"2023-05-02",
       "numberOfBookableSeats":9,
       "itineraries":[
          {
             "duration":"PT14H15M",
             "segments":[
                {
                   "departure":{
                      "iataCode":"SYD",
                      "terminal":"1",
                      "at":"2023-05-02T11:35:00"
                   },
                   "arrival":{
                      "iataCode":"MNL",
                      "terminal":"2",
                      "at":"2023-05-02T16:50:00"
                   },
                   "carrierCode":"PR",
                   "number":"212",
                   "aircraft":{
                      "code":"333"
                   },
                   "operating":{
                      "carrierCode":"PR"
                   },
                   "duration":"PT8H15M",
                   "id":"1",
                   "numberOfStops":0,
                   "blacklistedInEU":false
                },
                {
                   "departure":{
                      "iataCode":"MNL",
                      "terminal":"2",
                      "at":"2023-05-02T19:20:00"
                   },
                   "arrival":{
                      "iataCode":"BKK",
                      "at":"2023-05-02T21:50:00"
                   },
                   "carrierCode":"PR",
                   "number":"732",
                   "aircraft":{
                      "code":"321"
                   },
                   "operating":{
                      "carrierCode":"PR"
                   },
                   "duration":"PT3H30M",
                   "id":"2",
                   "numberOfStops":0,
                   "blacklistedInEU":false
                }
             ]
          }
       ],
       "price":{
          "currency":"EUR",
          "total":"368.23",
          "base":"253.00",
          "fees":[
             {
                "amount":"0.00",
                "type":"SUPPLIER"
             },
             {
                "amount":"0.00",
                "type":"TICKETING"
             }
          ],
          "grandTotal":"368.23"
       },
       "pricingOptions":{
          "fareType":[
             "PUBLISHED"
          ],
          "includedCheckedBagsOnly":true
       },
       "validatingAirlineCodes":[
          "PR"
       ],
       "travelerPricings":[
          {
             "travelerId":"1",
             "fareOption":"STANDARD",
             "travelerType":"ADULT",
             "price":{
                "currency":"EUR",
                "total":"368.23",
                "base":"253.00"
             },
             "fareDetailsBySegment":[
                {
                   "segmentId":"1",
                   "cabin":"ECONOMY",
                   "fareBasis":"EOBAU",
                   "class":"E",
                   "includedCheckedBags":{
                      "weight":30,
                      "weightUnit":"KG"
                   }
                },
                {
                   "segmentId":"2",
                   "cabin":"ECONOMY",
                   "fareBasis":"EOBAU",
                   "class":"E",
                   "includedCheckedBags":{
                      "weight":30,
                      "weightUnit":"KG"
                   }
                }
             ]
          }
       ]
    }
 ]

 export type filghtListType = typeof flightListDataFormat








