export const cityLists = [{"cityCode":"LBV","city":"LIBREVILLE","country":"가봉"},
{"cityCode":"ATH","city":"ATENES","country":"그리스"},
{"cityCode":"JMK","city":"MIKONOS","country":"그리스"},
{"cityCode":"LOS","city":"LAGOS","country":"나이지리아"},
{"cityCode":"PHC","city":"PORT HARCOURT","country":"나이지리아"},
{"cityCode":"KAD","city":"KADUNA","country":"나이지리아"},
{"cityCode":"CPT","city":"CAPETOWN","country":"남아프리카"},
{"cityCode":"AMS","city":"AMSTERDAM","country":"네덜란드"},
{"cityCode":"SPL","city":"SKIPOLE","country":"네덜란드"},
{"cityCode":"EIN","city":"EINDHOVEN","country":"네덜란드"},
{"cityCode":"KTM","city":"KATHMANDU","country":"네팔"},
{"cityCode":"SDN","city":"SANDANE","country":"노르웨이"},
{"cityCode":"OSL","city":"OSLO","country":"노르웨이"},
{"cityCode":"AKL","city":"AUCKLAND","country":"뉴질랜드"},
{"cityCode":"CHC","city":"CHRISTCHURCH","country":"뉴질랜드"},
{"cityCode":"TRG","city":"TAURANGA","country":"뉴질랜드"},
{"cityCode":"ODM","city":"ODM","country":"뉴질랜드"},
{"cityCode":"NOU","city":"NOUMEA","country":"뉴칼레도니아"},
{"cityCode":"PTN","city":"PINGDONG","country":"대만"},
{"cityCode":"RMQ","city":"TAICHUNG","country":"대만"},
{"cityCode":"TIN","city":"TAINAN","country":"대만"},
{"cityCode":"TNN","city":"TAINAN","country":"대만"},
{"cityCode":"TPE","city":"TAIPEI","country":"대만"},
{"cityCode":"TTT","city":"TAITUNG","country":"대만"},
{"cityCode":"TXG","city":"TAICHUNG","country":"대만"},
{"cityCode":"MZG","city":"MAKUNG","country":"대만"},
{"cityCode":"HUN","city":"HUALIEN","country":"대만"},
{"cityCode":"KHH","city":"KAOHSIUNG","country":"대만"},
{"cityCode":"BLL","city":"BILLUND","country":"덴마크"},
{"cityCode":"CPH","city":"COPENHAGEN","country":"덴마크"},
{"cityCode":"PNE","city":"PHILADELPHIA","country":"도미니카"},
{"cityCode":"BER","city":"BERLIN","country":"독일"},
{"cityCode":"BRE","city":"BREMEN","country":"독일"},
{"cityCode":"CGN","city":"COLOGNE/BONN","country":"독일"},
{"cityCode":"DRS","city":"DRESDEN","country":"독일"},
{"cityCode":"RMS","city":"RAMSTEIN","country":"독일"},
{"cityCode":"STR","city":"SHUTTGARETTE","country":"독일"},
{"cityCode":"TXL","city":"TEGEL(BERLIN)","country":"독일"},
{"cityCode":"XFW","city":"FINKENWEDER","country":"독일"},
{"cityCode":"MUC","city":"MUNCHEN","country":"독일"},
{"cityCode":"NUE","city":"NUREMBERG","country":"독일"},
{"cityCode":"FCN","city":"NORDHOLZ","country":"독일"},
{"cityCode":"FKB","city":"KALSLUHE","country":"독일"},
{"cityCode":"FRA","city":"FRANKFURT","country":"독일"},
{"cityCode":"HAJ","city":"HANOVER","country":"독일"},
{"cityCode":"HAM","city":"HAMBURG","country":"독일"},
{"cityCode":"HHN","city":"HAHN","country":"독일"},
{"cityCode":"LEJ","city":"LEIPJIG","country":"독일"},
{"cityCode":"VTE","city":"VIENTIANE","country":"라오스"},
{"cityCode":"RIX","city":"RIGA","country":"라트비아"},
{"cityCode":"ABA","city":"ABAKAN","country":"러시아"},
{"cityCode":"ABL","city":"ABALAN","country":"러시아"},
{"cityCode":"ARH","city":"ARHANGELSK","country":"러시아"},
{"cityCode":"AVV","city":"AVALON","country":"러시아"},
{"cityCode":"BAK","city":"BAKU","country":"러시아"},
{"cityCode":"BAX","city":"BARNAUL","country":"러시아"},
{"cityCode":"BKA","city":"MOSCOW-BYKOVO","country":"러시아"},
{"cityCode":"BQS","city":"BLAGOVESCHENSK","country":"러시아"},
{"cityCode":"BTK","city":"BRATSK","country":"러시아"},
{"cityCode":"CCK","city":"CAMCHASKI","country":"러시아"},
{"cityCode":"CEK","city":"CHELYABINSK","country":"러시아"},
{"cityCode":"CKL","city":"CHEKALOVSKY","country":"러시아"},
{"cityCode":"CKT","city":"CHIMKENT","country":"러시아"},
{"cityCode":"DMB","city":"ZHAMBYL","country":"러시아"},
{"cityCode":"DME","city":"DOMODEDOVO","country":"러시아"},
{"cityCode":"HMA","city":"KHANTY-MANSIYSK","country":"러시아"},
{"cityCode":"UUB","city":"RAMENSKOYE","country":"러시아"},
{"cityCode":"UUR","city":"TAGANROG","country":"러시아"},
{"cityCode":"AER","city":"ADLER SOCHI","country":"러시아"},
{"cityCode":"ROV","city":"ROSTOV","country":"러시아"},
{"cityCode":"SAK","city":"SAKHALINSK","country":"러시아"},
{"cityCode":"SCW","city":"SYKTYVKAR","country":"러시아"},
{"cityCode":"SVO","city":"SHEREMETYEVO","country":"러시아"},
{"cityCode":"SVX","city":"EKATERINBURG","country":"러시아"},
{"cityCode":"TOF","city":"TOMSK","country":"러시아"},
{"cityCode":"UFA","city":"UFA","country":"러시아"},
{"cityCode":"UKC","city":"MAGADAN","country":"러시아"},
{"cityCode":"ULY","city":"ULYANDVSK","country":"러시아"},
{"cityCode":"UMO","city":"OSTAFYEVO","country":"러시아"},
{"cityCode":"UMW","city":"KAUNAS","country":"러시아"},
{"cityCode":"UUD","city":"URANUTAE","country":"러시아"},
{"cityCode":"UUS","city":"YUZHNO SAKHALINSK","country":"러시아"},
{"cityCode":"VKO","city":"MOSCOW(VNUKOVO)","country":"러시아"},
{"cityCode":"VVO","city":"VLADIVOSTOK","country":"러시아"},
{"cityCode":"YKS","city":"YAKUTSK","country":"러시아"},
{"cityCode":"MCX","city":"MAKHACHKALA","country":"러시아"},
{"cityCode":"MMK","city":"MURMANSK","country":"러시아"},
{"cityCode":"MNS","city":"MANAS","country":"러시아"},
{"cityCode":"MOW","city":"MOSCOW","country":"러시아"},
{"cityCode":"MQF","city":"Maqnitoqorsk","country":"러시아"},
{"cityCode":"MSQ","city":"MINSK","country":"러시아"},
{"cityCode":"NAL","city":"NALCHIK","country":"러시아"},
{"cityCode":"NJC","city":"Nizhnevartovsk Airport","country":"러시아"},
{"cityCode":"NOZ","city":"NOVOKUZNETSK","country":"러시아"},
{"cityCode":"OMS","city":"OMSK","country":"러시아"},
{"cityCode":"OSS","city":"OSH","country":"러시아"},
{"cityCode":"OVB","city":"NOVOSIBIRSK","country":"러시아"},
{"cityCode":"PEE","city":"PERM","country":"러시아"},
{"cityCode":"PES","city":"PETROSABOSK","country":"러시아"},
{"cityCode":"PKC","city":"PETROPAVLOVSK","country":"러시아"},
{"cityCode":"DYR","city":"ANADYR","country":"러시아"},
{"cityCode":"DYU","city":"DUSHAMBE","country":"러시아"},
{"cityCode":"EVN","city":"EREVAN","country":"러시아"},
{"cityCode":"FEG","city":"FERGANA","country":"러시아"},
{"cityCode":"FRU","city":"FRUNZE","country":"러시아"},
{"cityCode":"GDX","city":"MAGADAN","country":"러시아"},
{"cityCode":"HTA","city":"CHITA","country":"러시아"},
{"cityCode":"IEV","city":"KIEV","country":"러시아"},
{"cityCode":"IKT","city":"IKT IRKUTSK","country":"러시아"},
{"cityCode":"KEJ","city":"KEMEROVO","country":"러시아"},
{"cityCode":"KHV","city":"HABAROBSK","country":"러시아"},
{"cityCode":"KIV","city":"KISHINEV","country":"러시아"},
{"cityCode":"KJA","city":"KRASNOJARSK","country":"러시아"},
{"cityCode":"KLD","city":"MIGALOF","country":"러시아"},
{"cityCode":"KUF","city":"SAMARA","country":"러시아"},
{"cityCode":"KUN","city":"KAUNAS","country":"러시아"},
{"cityCode":"KXK","city":"KOMSOMSKNAMUR","country":"러시아"},
{"cityCode":"KZN","city":"KAZAN","country":"러시아"},
{"cityCode":"LED","city":"LENINGRAD","country":"러시아"},
{"cityCode":"BEY","city":"BEIRUT","country":"레바논"},
{"cityCode":"BBU","city":"BUCHAREST","country":"루마니아"},
{"cityCode":"BEG","city":"BELGRADE","country":"루마니아"},
{"cityCode":"BUD","city":"BUCHAREST","country":"루마니아"},
{"cityCode":"BUH","city":"BUCHUREST","country":"루마니아"},
{"cityCode":"OTP","city":"BUCURESTI","country":"루마니아"},
{"cityCode":"RUN","city":"RUSAKA","country":"루안다"},
{"cityCode":"LUX","city":"LUXEMBOURG","country":"룩셈부르크"},
{"cityCode":"BEN","city":"BENGHAZI-BENINA","country":"리비아"},
{"cityCode":"TIP","city":"TRIPOLI","country":"리비아"},
{"cityCode":"MAJ","city":"MAJURO","country":"마셜제도"},
{"cityCode":"MFM","city":"MACAU","country":"마카오"},
{"cityCode":"BKI","city":"KOTA KINABALU","country":"말레이지아"},
{"cityCode":"BTU","city":"BINTULU","country":"말레이지아"},
{"cityCode":"SZB","city":"SULTAN ABDUL AZIZ","country":"말레이지아"},
{"cityCode":"LGK","city":"LANGKAWL","country":"말레이지아"},
{"cityCode":"MYY","city":"MIRI","country":"말레이지아"},
{"cityCode":"PEN","city":"PENANG","country":"말레이지아"},
{"cityCode":"JHB","city":"JOHOR BAHRU","country":"말레이지아"},
{"cityCode":"KCH","city":"KUCHING","country":"말레이지아"},
{"cityCode":"KUA","city":"KOOANTAN","country":"말레이지아"},
{"cityCode":"KUL","city":"KUALA LUMPUR","country":"말레이지아"},
{"cityCode":"LBU","city":"LABUAN","country":"말레이지아"},
{"cityCode":"DGO","city":"DURANGO","country":"멕시코"},
{"cityCode":"TIJ","city":"TIJUANA","country":"멕시코"},
{"cityCode":"TLC","city":"TOLUCA","country":"멕시코"},
{"cityCode":"MEX","city":"MEXICO","country":"멕시코"},
{"cityCode":"FEZ","city":"FEZ SAISS","country":"모로코"},
{"cityCode":"MLE","city":"MALE","country":"몰디브공화국"},
{"cityCode":"MLA","city":"MALTA","country":"몰타공화국"},
{"cityCode":"ULN","city":"ULAAN BAATAR","country":"몽고"},
{"cityCode":"ACY","city":"ATLANTIC CITY","country":"미국"},
{"cityCode":"ADK","city":"ADAK","country":"미국"},
{"cityCode":"ADQ","city":"KODIAK ALS","country":"미국"},
{"cityCode":"AKN","city":"KING SALMAN","country":"미국"},
{"cityCode":"ALB","city":"ALBANY","country":"미국"},
{"cityCode":"AMA","city":"AMARILLO","country":"미국"},
{"cityCode":"ANC","city":"ANCHORAGE","country":"미국"},
{"cityCode":"AND","city":"ANDERSEN","country":"미국"},
{"cityCode":"ASC","city":"DEADHORSE","country":"미국"},
{"cityCode":"ATL","city":"ATLANTA","country":"미국"},
{"cityCode":"AUS","city":"AUSTIN TEXAS","country":"미국"},
{"cityCode":"BDL","city":"BRADLEY INTL AIRPORT","country":"미국"},
{"cityCode":"BET","city":"BETHEL","country":"미국"},
{"cityCode":"BFI","city":"BOEING FIEL","country":"미국"},
{"cityCode":"BFN","city":"MOBIL","country":"미국"},
{"cityCode":"BGR","city":"BANGOR","country":"미국"},
{"cityCode":"BNA","city":"NASHVILLE","country":"미국"},
{"cityCode":"BOS","city":"BOSTON","country":"미국"},
{"cityCode":"BUR","city":"BURBANK","country":"미국"},
{"cityCode":"BWI","city":"BALTIMORE","country":"미국"},
{"cityCode":"CBG","city":"CAMBRIDGE","country":"미국"},
{"cityCode":"CDB","city":"COLD BAY","country":"미국"},
{"cityCode":"CHI","city":"CHICAGO","country":"미국"},
{"cityCode":"CHS","city":"CHARLESTON MUNICIPAL","country":"미국"},
{"cityCode":"CLT","city":"CHARLOTTE","country":"미국"},
{"cityCode":"CMH","city":"COLUMBUS","country":"미국"},
{"cityCode":"CPM","city":"COMPTON","country":"미국"},
{"cityCode":"CVG","city":"CINCINNATI","country":"미국"},
{"cityCode":"DAL","city":"DALLAS","country":"미국"},
{"cityCode":"DAY","city":"DAYTON","country":"미국"},
{"cityCode":"DCA","city":"WASHINGTON NATL","country":"미국"},
{"cityCode":"DEN","city":"DENVER","country":"미국"},
{"cityCode":"DET","city":"DETROIT","country":"미국"},
{"cityCode":"DFW","city":"DALLAS/FORT WORTH","country":"미국"},
{"cityCode":"DLH","city":"DULUTH INTL","country":"미국"},
{"cityCode":"DOV","city":"Dover-Cheswold AFB","country":"미국"},
{"cityCode":"DSM","city":"DES MOINES","country":"미국"},
{"cityCode":"DTT","city":"DETROIT","country":"미국"},
{"cityCode":"DTW","city":"DETROIT METROPOLITAN","country":"미국"},
{"cityCode":"DWF","city":"DAYTON WRIGHR","country":"미국"},
{"cityCode":"SSC","city":"SHAW AFB","country":"미국"},
{"cityCode":"PVU","city":"PROVO MUNICIPAL","country":"미국"},
{"cityCode":"CLD","city":"CARLSBAD","country":"미국"},
{"cityCode":"MHV","city":"MOJAVE","country":"미국"},
{"cityCode":"CRQ","city":"CARLSBAD","country":"미국"},
{"cityCode":"PTK","city":"PONTIAC","country":"미국"},
{"cityCode":"PWK","city":"CHICAGO","country":"미국"},
{"cityCode":"RIV","city":"MARCH","country":"미국"},
{"cityCode":"RNO","city":"RENO","country":"미국"},
{"cityCode":"ROG","city":"ROGERS","country":"미국"},
{"cityCode":"ROR","city":"COROR","country":"미국"},
{"cityCode":"ROW","city":"ROSWELL","country":"미국"},
{"cityCode":"SAN","city":"SAN DIEGO","country":"미국"},
{"cityCode":"SAT","city":"SANANTINO","country":"미국"},
{"cityCode":"SBA","city":"SANTA BARBARA","country":"미국"},
{"cityCode":"SEA","city":"SEATTLE","country":"미국"},
{"cityCode":"SFO","city":"SAN FRANCISCO","country":"미국"},
{"cityCode":"SGF","city":"SPRINGFIELD","country":"미국"},
{"cityCode":"SHD","city":"STAUNTON","country":"미국"},
{"cityCode":"SJC","city":"SAN JOSE CAL","country":"미국"},
{"cityCode":"SKA","city":"SPOKANE","country":"미국"},
{"cityCode":"SLC","city":"SALT LAKE CITY","country":"미국"},
{"cityCode":"SMF","city":"SACRAMENTO","country":"미국"},
{"cityCode":"SMX","city":"SANTA MARIA","country":"미국"},
{"cityCode":"SNP","city":"ST PAUL ISLAND","country":"미국"},
{"cityCode":"SPN","city":"SAIPAN","country":"미국"},
{"cityCode":"SPS","city":"WICHITA","country":"미국"},
{"cityCode":"STL","city":"ST LOUIS","country":"미국"},
{"cityCode":"STP","city":"ST PAUL MINN","country":"미국"},
{"cityCode":"SUU","city":"TRAVIS","country":"미국"},
{"cityCode":"SWF","city":"NEWBURGH","country":"미국"},
{"cityCode":"SYA","city":"SHEMA","country":"미국"},
{"cityCode":"TCM","city":"McCHORD","country":"미국"},
{"cityCode":"TEB","city":"TETERBORO","country":"미국"},
{"cityCode":"TKK","city":"TRUK","country":"미국"},
{"cityCode":"TOL","city":"TOLEDO","country":"미국"},
{"cityCode":"TUL","city":"TULSA","country":"미국"},
{"cityCode":"TUS","city":"TUCSON","country":"미국"},
{"cityCode":"UAM","city":"ANDERSON","country":"미국"},
{"cityCode":"VCV","city":"VICTORVILLE","country":"미국"},
{"cityCode":"VNY","city":"VANNUYS","country":"미국"},
{"cityCode":"VPC","city":"CATERSBILL","country":"미국"},
{"cityCode":"WAS","city":"WASHINGTON","country":"미국"},
{"cityCode":"WKE","city":"WEIKE","country":"미국"},
{"cityCode":"XNA","city":"FAYETTEVILLE","country":"미국"},
{"cityCode":"YIP","city":"DETROIT WILLOW RUN","country":"미국"},
{"cityCode":"LGA","city":"NEW YORK LA GUARDIA","country":"미국"},
{"cityCode":"LGB","city":"LONG BEACH","country":"미국"},
{"cityCode":"LIH","city":"LIHUE","country":"미국"},
{"cityCode":"LIT","city":"LITTLAC","country":"미국"},
{"cityCode":"LTS","city":"ALTUS","country":"미국"},
{"cityCode":"LUK","city":"CINCINNATI","country":"미국"},
{"cityCode":"LUT","city":"LUTON","country":"미국"},
{"cityCode":"MCI","city":"KANSAS","country":"미국"},
{"cityCode":"MCO","city":"ORLANDO","country":"미국"},
{"cityCode":"MDW","city":"SHICAGO MIDWAY","country":"미국"},
{"cityCode":"MDY","city":"MIDWAY","country":"미국"},
{"cityCode":"MEM","city":"MEMPHIS","country":"미국"},
{"cityCode":"MGM","city":"MONTGOMERY DANNELLY","country":"미국"},
{"cityCode":"MHR","city":"SACRAMENTO","country":"미국"},
{"cityCode":"MIA","city":"MIAMI","country":"미국"},
{"cityCode":"MIC","city":"MICRONESIA","country":"미국"},
{"cityCode":"MKC","city":"KANSAS CITY","country":"미국"},
{"cityCode":"MKE","city":"MILWACKEE","country":"미국"},
{"cityCode":"MMU","city":"MORRISTOWN MUNICPAN","country":"미국"},
{"cityCode":"MRY","city":"MONTEREY","country":"미국"},
{"cityCode":"MSP","city":"MINNEAPOLIS/ST.PAUL","country":"미국"},
{"cityCode":"MSY","city":"NEW ORLEANS","country":"미국"},
{"cityCode":"MTJ","city":"MONTROSE","country":"미국"},
{"cityCode":"MZJ","city":"MARANA","country":"미국"},
{"cityCode":"NGF","city":"KANEOHE BAY MCAF","country":"미국"},
{"cityCode":"NGU","city":"NORFOLK","country":"미국"},
{"cityCode":"NKW","city":"DIEGO GARSIA","country":"미국"},
{"cityCode":"NOM","city":"NOME","country":"미국"},
{"cityCode":"NUW","city":"WHIDBEY","country":"미국"},
{"cityCode":"NYC","city":"NEWYORK","country":"미국"},
{"cityCode":"NYL","city":"YUMA MCAS","country":"미국"},
{"cityCode":"OAK","city":"OAKLAND","country":"미국"},
{"cityCode":"OCK","city":"OKLAHOMA","country":"미국"},
{"cityCode":"OGG","city":"KAHULUI","country":"미국"},
{"cityCode":"OMA","city":"OHMA","country":"미국"},
{"cityCode":"OME","city":"NOME","country":"미국"},
{"cityCode":"ONT","city":"ONTARIO","country":"미국"},
{"cityCode":"ORD","city":"CHICAGO O'HARE","country":"미국"},
{"cityCode":"ORL","city":"ORLANDO","country":"미국"},
{"cityCode":"OSC","city":"OSCODA","country":"미국"},
{"cityCode":"PAE","city":"EVERETT","country":"미국"},
{"cityCode":"PBI","city":"WESTPLMBEACH","country":"미국"},
{"cityCode":"PDX","city":"PORTLAND","country":"미국"},
{"cityCode":"PEC","city":"PELICAN","country":"미국"},
{"cityCode":"PHL","city":"PHILADELPHIA","country":"미국"},
{"cityCode":"PHX","city":"PHOENIX","country":"미국"},
{"cityCode":"PIE","city":"ST PETERSBURG","country":"미국"},
{"cityCode":"PKO","city":"KONA","country":"미국"},
{"cityCode":"PSP","city":"PAM SPRINGS","country":"미국"},
{"cityCode":"EDF","city":"ELMENDORF","country":"미국"},
{"cityCode":"EIL","city":"ELSIN","country":"미국"},
{"cityCode":"EWR","city":"NEWYORK NEWARK","country":"미국"},
{"cityCode":"FAI","city":"FAIRBANKS","country":"미국"},
{"cityCode":"FLL","city":"FT. LAUDERDALE","country":"미국"},
{"cityCode":"FRG","city":"FARMINGDALE","country":"미국"},
{"cityCode":"GRR","city":"GRAND RAPIDS","country":"미국"},
{"cityCode":"GTF","city":"GREATPOLS","country":"미국"},
{"cityCode":"GUM","city":"GUAM AGANA FIELD","country":"미국"},
{"cityCode":"HGR","city":"HAGERSTOWN","country":"미국"},
{"cityCode":"HHH","city":"HILTON HEAD ISLAND","country":"미국"},
{"cityCode":"HIK","city":"HAIKAM","country":"미국"},
{"cityCode":"HIO","city":"PORTLAND HILLSBORO","country":"미국"},
{"cityCode":"HMN","city":"ALAMOGORDO","country":"미국"},
{"cityCode":"HNL","city":"HONOLULU","country":"미국"},
{"cityCode":"HON","city":"HORON","country":"미국"},
{"cityCode":"HOU","city":"HOUSTON","country":"미국"},
{"cityCode":"HPN","city":"WESTCHESTER COUNTY","country":"미국"},
{"cityCode":"HSV","city":"HUNTSVILLE","country":"미국"},
{"cityCode":"IAB","city":"MCCONNELL","country":"미국"},
{"cityCode":"IAD","city":"D.C DULLES","country":"미국"},
{"cityCode":"IAH","city":"HOUSTON","country":"미국"},
{"cityCode":"IAI","city":"KONA","country":"미국"},
{"cityCode":"ICT","city":"WICHITA","country":"미국"},
{"cityCode":"ILM","city":"WILMINGTON","country":"미국"},
{"cityCode":"ILN","city":"WILMINGTON","country":"미국"},
{"cityCode":"IND","city":"INDIANAPOLIS","country":"미국"},
{"cityCode":"JAX","city":"JACKSONVILLE","country":"미국"},
{"cityCode":"JFK","city":"JOHN F.KENNEDY","country":"미국"},
{"cityCode":"KKI","city":"ST THOMAS ISLAND","country":"미국"},
{"cityCode":"KOA","city":"KONA","country":"미국"},
{"cityCode":"LAS","city":"LAS VEGAS","country":"미국"},
{"cityCode":"LAX","city":"LOS ANGELES","country":"미국"},
{"cityCode":"LCK","city":"LICENBEK","country":"미국"},
{"cityCode":"RGT","city":"MAMTU","country":"미얀마"},
{"cityCode":"RGN","city":"YANGON","country":"미얀마"},
{"cityCode":"NYU","city":"MYANMAR BAGAN","country":"미얀마"},
{"cityCode":"PNI","city":"POHNPEI","country":"미크로네시아"},
{"cityCode":"BAH","city":"BAHRAIN","country":"바레인"},
{"cityCode":"CGP","city":"CHITTAGONG","country":"방글라데시"},
{"cityCode":"DAC","city":"DHAKA","country":"방글라데시"},
{"cityCode":"GZR","city":"KURMITOLA","country":"방글라데시"},
{"cityCode":"CCS","city":"CARACAS","country":"베네수엘라"},
{"cityCode":"DAD","city":"DANANG","country":"베트남"},
{"cityCode":"SGN","city":"HOCHIMIN","country":"베트남"},
{"cityCode":"HAN","city":"HANOI","country":"베트남"},
{"cityCode":"HUI","city":"HUI HUE","country":"베트남"},
{"cityCode":"BRU","city":"BRUSSELS","country":"벨기에"},
{"cityCode":"LGG","city":"LIEGE-BIERSET","country":"벨기에"},
{"cityCode":"PBH","city":"PARO","country":"부탄"},
{"cityCode":"SNK","city":"SUNDUK","country":"북한"},
{"cityCode":"FNJ","city":"PYUNGYANG","country":"북한"},
{"cityCode":"SOF","city":"SOPIA","country":"불가리아"},
{"cityCode":"BAS","city":"BUENOSAIRES","country":"브라질"},
{"cityCode":"VCP","city":"VIRACOPOS","country":"브라질"},
{"cityCode":"RIO","city":"RIO DE JANERIO","country":"브라질"},
{"cityCode":"MGF","city":"MARINGA-IN-PARANA","country":"브라질"},
{"cityCode":"PHI","city":"SICAM","country":"브라질"},
{"cityCode":"GIG","city":"RIO DE JANEIRO","country":"브라질"},
{"cityCode":"GRU","city":"SAO PAULO","country":"브라질"},
{"cityCode":"IGU","city":"IGUASSU FALLS","country":"브라질"},
{"cityCode":"BWN","city":"BANDAR SERI BEGAWAN","country":"브루나이"},
{"cityCode":"DWN","city":"DWN","country":"브루나이"},
{"cityCode":"DHA","city":"DHAHRAN","country":"사우디아라비아"},
{"cityCode":"DMM","city":"DAMMAM","country":"사우디아라비아"},
{"cityCode":"RUH","city":"RIYADH","country":"사우디아라비아"},
{"cityCode":"JED","city":"JEDDAH","country":"사우디아라비아"},
{"cityCode":"DKR","city":"DAKAR","country":"세네갈"},
{"cityCode":"MGQ","city":"MOGADISHU","country":"소말리아"},
{"cityCode":"KRT","city":"KHARTOUM","country":"수단"},
{"cityCode":"CMB","city":"COLOMBO","country":"스리랑카"},
{"cityCode":"ARN","city":"STOCKHOLM ARLANDA","country":"스웨덴"},
{"cityCode":"BMA","city":"STOCKHOLM","country":"스웨덴"},
{"cityCode":"STO","city":"STOCKHOLM","country":"스웨덴"},
{"cityCode":"LLA","city":"LULEA","country":"스웨덴"},
{"cityCode":"MMA","city":"MALMO","country":"스웨덴"},
{"cityCode":"MMX","city":"MALMO","country":"스웨덴"},
{"cityCode":"NYO","city":"SKAYSTA","country":"스웨덴"},
{"cityCode":"OSK","city":"OSKARSHAMN","country":"스웨덴"},
{"cityCode":"GOT","city":"GOTEBORG","country":"스웨덴"},
{"cityCode":"BSL","city":"BASEL","country":"스위스"},
{"cityCode":"ZRH","city":"ZURICH","country":"스위스"},
{"cityCode":"LUG","city":"LUGANO","country":"스위스"},
{"cityCode":"GVA","city":"GENEVA","country":"스위스"},
{"cityCode":"BCN","city":"BARCELONA","country":"스페인"},
{"cityCode":"TOJ","city":"MADRID","country":"스페인"},
{"cityCode":"VIT","city":"VICTORIA","country":"스페인"},
{"cityCode":"VLC","city":"VALENCIA","country":"스페인"},
{"cityCode":"MAD","city":"MADRID BARAJAS","country":"스페인"},
{"cityCode":"PMI","city":"PALMA DE MALLORCA","country":"스페인"},
{"cityCode":"BTS","city":"BRATISLAVA","country":"슬로바키아"},
{"cityCode":"QPG","city":"PAYALEBAR","country":"싱가포르"},
{"cityCode":"SIN","city":"SINGAPORE","country":"싱가포르"},
{"cityCode":"XSP","city":"SELETAR","country":"싱가포르"},
{"cityCode":"AAN","city":"AI AIN","country":"아랍에미레이트"},
{"cityCode":"AUH","city":"ABU DHABI","country":"아랍에미레이트"},
{"cityCode":"DXB","city":"DUBAI","country":"아랍에미레이트"},
{"cityCode":"SHJ","city":"SHARJAH","country":"아랍에미레이트"},
{"cityCode":"NHD","city":"MINHAD AB Military","country":"아랍에미레이트"},
{"cityCode":"FJR","city":"FUJAIRAH","country":"아랍에미레이트"},
{"cityCode":"KEF","city":"ROYKJAVIK KEFLAVIK","country":"아이슬랜드"},
{"cityCode":"DUB","city":"DUBLIN","country":"아일랜드"},
{"cityCode":"SNN","city":"SHANNON","country":"아일랜드"},
{"cityCode":"GYD","city":"AZERBAIJAN","country":"아제르바이잔"},
{"cityCode":"BST","city":"BOST","country":"아프가니스탄"},
{"cityCode":"OAA","city":"BAGRAM","country":"아프가니스탄"},
{"cityCode":"KBL","city":"KABUL K. RAWWASH","country":"아프가니스탄"},
{"cityCode":"ALG","city":"ALGIERS","country":"알제리"},
{"cityCode":"CTI","city":"CUITO-CUANAVALA","country":"앙골라"},
{"cityCode":"TLL","city":"TALLINN","country":"에스토니아"},
{"cityCode":"BDA","city":"BERMUDA","country":"영국"},
{"cityCode":"BFS","city":"BELFAST","country":"영국"},
{"cityCode":"BQH","city":"BIGGIN HILL","country":"영국"},
{"cityCode":"ABZ","city":"ABERDEEN","country":"영국"},
{"cityCode":"REK","city":"REYKJAVIK APT ICELAN","country":"영국"},
{"cityCode":"SOU","city":"SOUTHAMPTON","country":"영국"},
{"cityCode":"STN","city":"STENSTED","country":"영국"},
{"cityCode":"LGW","city":"LONDON GATWICK","country":"영국"},
{"cityCode":"LHR","city":"LONDON HEATHROW","country":"영국"},
{"cityCode":"LON","city":"LONDON","country":"영국"},
{"cityCode":"LTN","city":"LUTON","country":"영국"},
{"cityCode":"MAN","city":"MANCHESTER","country":"영국"},
{"cityCode":"PIK","city":"PRESTWICK","country":"영국"},
{"cityCode":"EDI","city":"EDINBURGH","country":"영국"},
{"cityCode":"EMA","city":"NOTTINGHAM EAST MID","country":"영국"},
{"cityCode":"FAB","city":"FARNBOROUGH","country":"영국"},
{"cityCode":"ADE","city":"ADEN","country":"예맨"},
{"cityCode":"MCT","city":"MUSCAT","country":"오만"},
{"cityCode":"SZG","city":"SAZBURG","country":"오스트리아"},
{"cityCode":"VIE","city":"AUSTRIA VIENNA","country":"오스트리아"},
{"cityCode":"AMM","city":"AMMAN","country":"요르단"},
{"cityCode":"AQJ","city":"AQABA","country":"요르단"},
{"cityCode":"AZN","city":"ANDIZAHAN","country":"우즈베키스탄"},
{"cityCode":"BHK","city":"BUKHARA","country":"우즈베키스탄"},
{"cityCode":"NVI","city":"NAVOI","country":"우즈베키스탄"},
{"cityCode":"SKD","city":"SAMARKAND","country":"우즈베키스탄"},
{"cityCode":"TAS","city":"TASHKENT","country":"우즈베키스탄"},
{"cityCode":"NMA","city":"NAMANGAN","country":"우즈베키스탄"},
{"cityCode":"NMG","city":"NAMANGAN","country":"우즈베키스탄"},
{"cityCode":"KBP","city":"BORYSPIL","country":"우크라이나"},
{"cityCode":"GML","city":"HOSTOMEL","country":"우크라이나"},
{"cityCode":"KWG","city":"LOZUVATIKA","country":"우크라이나"},
{"cityCode":"ADD","city":"ADDIS ABABA","country":"이디오피아"},
{"cityCode":"AWA","city":"AWASA","country":"이디오피아"},
{"cityCode":"SDA","city":"BAGHDAD SADDAM","country":"이라크"},
{"cityCode":"IKA","city":"TEHRAN","country":"이란"},
{"cityCode":"THR","city":"TEHRAN","country":"이란"},
{"cityCode":"MHD","city":"MASHAD","country":"이란"},
{"cityCode":"IFN","city":"ISFAHAN","country":"이란"},
{"cityCode":"TLV","city":"TEL AVIV BLAGNAC","country":"이스라엘"},
{"cityCode":"CAI","city":"CAIRO","country":"이집트"},
{"cityCode":"CIA","city":"ROME","country":"이탈리아"},
{"cityCode":"LIN","city":"MILANO","country":"이탈리아"},
{"cityCode":"ROM","city":"ROME","country":"이탈리아"},
{"cityCode":"VBS","city":"BRESCIA","country":"이탈리아"},
{"cityCode":"VCE","city":"VENICE","country":"이탈리아"},
{"cityCode":"VCX","city":"BRESCIA","country":"이탈리아"},
{"cityCode":"MIL","city":"MILANO","country":"이탈리아"},
{"cityCode":"MXP","city":"MILAN MALPENSA","country":"이탈리아"},
{"cityCode":"PSA","city":"PISA","country":"이탈리아"},
{"cityCode":"FCO","city":"ROME LEONARDO DA VIN","country":"이탈리아"},
{"cityCode":"AMD","city":"AHMEDABAD","country":"인도"},
{"cityCode":"BOM","city":"MUMBAI","country":"인도"},
{"cityCode":"CCU","city":"CALCUTTA","country":"인도"},
{"cityCode":"DEL","city":"DELHI","country":"인도"},
{"cityCode":"AGR","city":"AGRA","country":"인도"},
{"cityCode":"LKO","city":"LUCKNOW","country":"인도"},
{"cityCode":"MAA","city":"MADRAS","country":"인도"},
{"cityCode":"NVY","city":"NEYVELI INDIA","country":"인도"},
{"cityCode":"OHY","city":"HADYBAD","country":"인도"},
{"cityCode":"OZI","city":"OZAR","country":"인도"},
{"cityCode":"HYD","city":"HYDERABAD","country":"인도"},
{"cityCode":"JAI","city":"JAIPUR","country":"인도"},
{"cityCode":"BCH","city":"BAUCAU","country":"인도네시아"},
{"cityCode":"BIK","city":"BIAK","country":"인도네시아"},
{"cityCode":"BLR","city":"BANGALORE","country":"인도네시아"},
{"cityCode":"BPN","city":"BALIKPAPAN","country":"인도네시아"},
{"cityCode":"BTH","city":"BATAM","country":"인도네시아"},
{"cityCode":"CGK","city":"JAKARTA","country":"인도네시아"},
{"cityCode":"DPS","city":"DENPASAR","country":"인도네시아"},
{"cityCode":"SUB","city":"SURABAYA","country":"인도네시아"},
{"cityCode":"MBC","city":"MANADO","country":"인도네시아"},
{"cityCode":"MDC","city":"MANADO","country":"인도네시아"},
{"cityCode":"MES","city":"MEDAN POLONIA","country":"인도네시아"},
{"cityCode":"HLP","city":"JAKARRA HALIM","country":"인도네시아"},
{"cityCode":"JKT","city":"JAKARTA","country":"인도네시아"},
{"cityCode":"LAH","city":"LABUHA","country":"인도네시아"},
{"cityCode":"AKJ","city":"ASAHIKAWA","country":"일본"},
{"cityCode":"AOJ","city":"AOMORI","country":"일본"},
{"cityCode":"AXT","city":"AKITA","country":"일본"},
{"cityCode":"CTS","city":"SAPPORO","country":"일본"},
{"cityCode":"DDJ","city":"MYJ","country":"일본"},
{"cityCode":"DNA","city":"ODINAWA","country":"일본"},
{"cityCode":"YOK","city":"YOKOHAMA","country":"일본"},
{"cityCode":"RJO","city":"IWAKUNI","country":"일본"},
{"cityCode":"CHO","city":"CHOFU","country":"일본"},
{"cityCode":"TSJ","city":"TSUSHIMA","country":"일본"},
{"cityCode":"MYZ","city":"MACHYAMA","country":"일본"},
{"cityCode":"UKB","city":"KOBE","country":"일본"},
{"cityCode":"QOM","city":"OMIYA","country":"일본"},
{"cityCode":"SDJ","city":"SENDAI","country":"일본"},
{"cityCode":"SHB","city":"NAKASHIBETSU","country":"일본"},
{"cityCode":"SHM","city":"SHIRAHAMA","country":"일본"},
{"cityCode":"SPK","city":"SAPPORO","country":"일본"},
{"cityCode":"SYO","city":"SHONAI","country":"일본"},
{"cityCode":"TAK","city":"TAKAMATSU","country":"일본"},
{"cityCode":"TJH","city":"TOYOKA","country":"일본"},
{"cityCode":"TKS","city":"TOKUSHIMA","country":"일본"},
{"cityCode":"TOY","city":"TOYAMA","country":"일본"},
{"cityCode":"TTJ","city":"TOTTORI","country":"일본"},
{"cityCode":"TYO","city":"TOKYO","country":"일본"},
{"cityCode":"UBJ","city":"UBE","country":"일본"},
{"cityCode":"WKJ","city":"WAKANAYI","country":"일본"},
{"cityCode":"YGJ","city":"YONAGO","country":"일본"},
{"cityCode":"MBE","city":"MATHMOTO","country":"일본"},
{"cityCode":"MMB","city":"MEMAMBETSU","country":"일본"},
{"cityCode":"MMJ","city":"MATSUMOTO","country":"일본"},
{"cityCode":"MSJ","city":"MISAWA","country":"일본"},
{"cityCode":"MYJ","city":"MATSUYAMA","country":"일본"},
{"cityCode":"NGO","city":"NAGOYA","country":"일본"},
{"cityCode":"NGS","city":"NAGASAKI","country":"일본"},
{"cityCode":"NJA","city":"ATSUKI","country":"일본"},
{"cityCode":"NKM","city":"NAGOYA/KOMAKI","country":"일본"},
{"cityCode":"NRD","city":"TOKYO","country":"일본"},
{"cityCode":"NRT","city":"TOKYO NARITA","country":"일본"},
{"cityCode":"NTQ","city":"NODO","country":"일본"},
{"cityCode":"OBO","city":"OBIHIRO","country":"일본"},
{"cityCode":"OIT","city":"OITA","country":"일본"},
{"cityCode":"OKA","city":"OKINAWA","country":"일본"},
{"cityCode":"OKD","city":"SAPPORO-OKADAMA","country":"일본"},
{"cityCode":"OKI","city":"OKI ISLAND","country":"일본"},
{"cityCode":"OKJ","city":"OKAYAMA","country":"일본"},
{"cityCode":"OKO","city":"YOKODA","country":"일본"},
{"cityCode":"ONJ","city":"OTATE","country":"일본"},
{"cityCode":"OSA","city":"OSAKA","country":"일본"},
{"cityCode":"FKJ","city":"FUKUI","country":"일본"},
{"cityCode":"FKS","city":"FUKUSHIMA","country":"일본"},
{"cityCode":"FTM","city":"FUTEMA","country":"일본"},
{"cityCode":"FUK","city":"FUKUOKA","country":"일본"},
{"cityCode":"GAJ","city":"YAMAGATA","country":"일본"},
{"cityCode":"HIJ","city":"HIROSHIMA","country":"일본"},
{"cityCode":"HKD","city":"HAKODATE","country":"일본"},
{"cityCode":"HKJ","city":"ASAHIGA","country":"일본"},
{"cityCode":"HNA","city":"MORIOKA","country":"일본"},
{"cityCode":"HND","city":"TOKYO HANEDA","country":"일본"},
{"cityCode":"HSG","city":"SAGA","country":"일본"},
{"cityCode":"IKN","city":"IWAKUNI","country":"일본"},
{"cityCode":"ITM","city":"ITAMI(NARITA)","country":"일본"},
{"cityCode":"IWJ","city":"IWAMI","country":"일본"},
{"cityCode":"IZO","city":"IZUMO","country":"일본"},
{"cityCode":"KCZ","city":"KOCHI","country":"일본"},
{"cityCode":"KIJ","city":"NIIGATA","country":"일본"},
{"cityCode":"KIX","city":"OSAKA KANSAI","country":"일본"},
{"cityCode":"KKJ","city":"KITA KYUSHU","country":"일본"},
{"cityCode":"KMI","city":"MIYAZAKI","country":"일본"},
{"cityCode":"KMJ","city":"KUMAMOTO","country":"일본"},
{"cityCode":"KMQ","city":"KOMATSU","country":"일본"},
{"cityCode":"KOJ","city":"KAGOSHIMA","country":"일본"},
{"cityCode":"KUH","city":"KUSHIRO","country":"일본"},
{"cityCode":"CAN","city":"GUANGZHOU BAIYUN","country":"중국"},
{"cityCode":"CGO","city":"ZHENGZHOU","country":"중국"},
{"cityCode":"CGQ","city":"CHANGCHUN","country":"중국"},
{"cityCode":"CKG","city":"CHONGQING","country":"중국"},
{"cityCode":"CSX","city":"CHANGSHA","country":"중국"},
{"cityCode":"CTU","city":"CHENGDU","country":"중국"},
{"cityCode":"CZX","city":"CHANGZHOU","country":"중국"},
{"cityCode":"DDG","city":"DANDONG","country":"중국"},
{"cityCode":"DLC","city":"DALIAN","country":"중국"},
{"cityCode":"DYG","city":"DAYONG","country":"중국"},
{"cityCode":"YNJ","city":"YANJI","country":"중국"},
{"cityCode":"YNT","city":"YANTAI","country":"중국"},
{"cityCode":"YNZ","city":"YANCHEN","country":"중국"},
{"cityCode":"PVG","city":"PUDONG","country":"중국"},
{"cityCode":"SHA","city":"HONGQIAO","country":"중국"},
{"cityCode":"SHE","city":"SHENYANG","country":"중국"},
{"cityCode":"SIA","city":"XI AN XIGUAN","country":"중국"},
{"cityCode":"SJW","city":"SHIJIAZHUANG","country":"중국"},
{"cityCode":"SWA","city":"SHANTOU","country":"중국"},
{"cityCode":"SYX","city":"SANYA","country":"중국"},
{"cityCode":"SZX","city":"SHENZHEN","country":"중국"},
{"cityCode":"TAO","city":"QINGDAO","country":"중국"},
{"cityCode":"TJM","city":"TIUMEN","country":"중국"},
{"cityCode":"TNA","city":"JINAN","country":"중국"},
{"cityCode":"TSN","city":"TIAN JIN","country":"중국"},
{"cityCode":"TXN","city":"TUNXI","country":"중국"},
{"cityCode":"TYN","city":"TAIYUAN","country":"중국"},
{"cityCode":"URC","city":"URUMQI","country":"중국"},
{"cityCode":"WEH","city":"WEIHAI","country":"중국"},
{"cityCode":"WUH","city":"WUHAN","country":"중국"},
{"cityCode":"XIY","city":"XIANYANG","country":"중국"},
{"cityCode":"XMN","city":"XIAMEN","country":"중국"},
{"cityCode":"LYG","city":"LAYONG","country":"중국"},
{"cityCode":"MDG","city":"MUDAN JIANG","country":"중국"},
{"cityCode":"NGB","city":"NINGBD","country":"중국"},
{"cityCode":"NKG","city":"NANJING","country":"중국"},
{"cityCode":"NNG","city":"NANRING","country":"중국"},
{"cityCode":"PEK","city":"BEIGING","country":"중국"},
{"cityCode":"FOC","city":"FUZHOU","country":"중국"},
{"cityCode":"HAK","city":"HAIKOU","country":"중국"},
{"cityCode":"HET","city":"HOHHOT","country":"중국"},
{"cityCode":"HFE","city":"HEPEI","country":"중국"},
{"cityCode":"HGH","city":"HANGZHOU","country":"중국"},
{"cityCode":"HHA","city":"HUANGHUA","country":"중국"},
{"cityCode":"HRB","city":"HARBIN","country":"중국"},
{"cityCode":"IQN","city":"QINGYANG","country":"중국"},
{"cityCode":"KHN","city":"NANCHANG","country":"중국"},
{"cityCode":"KMG","city":"KUNMING","country":"중국"},
{"cityCode":"KOW","city":"GANZHOU","country":"중국"},
{"cityCode":"KWE","city":"GUIYANG","country":"중국"},
{"cityCode":"KWL","city":"GUILIN","country":"중국"},
{"cityCode":"LAD","city":"LUANDA","country":"중앙아프리카"},
{"cityCode":"JIB","city":"JIBUTY","country":"지부티"},
{"cityCode":"PRG","city":"PRAGUE","country":"체코"},
{"cityCode":"SCL","city":"SANTIAGO","country":"칠레"},
{"cityCode":"AKX","city":"AKTYUBINSK","country":"카자흐스탄"},
{"cityCode":"ALA","city":"ALMA ATA","country":"카자흐스탄"},
{"cityCode":"CIT","city":"CHIMKENT","country":"카자흐스탄"},
{"cityCode":"GUW","city":"ATYRAU","country":"카자흐스탄"},
{"cityCode":"PWQ","city":"PAVLODAR","country":"카자흐스탄"},
{"cityCode":"TSE","city":"ASTANA","country":"카자흐스탄"},
{"cityCode":"KGF","city":"KARAGANDA","country":"카자흐스탄"},
{"cityCode":"KZA","city":"KAZAKHSTAN","country":"카자흐스탄"},
{"cityCode":"DOH","city":"DOHA","country":"카타르"},
{"cityCode":"IUD","city":"AL UDEID","country":"카타르"},
{"cityCode":"REP","city":"SIEM REAP","country":"캄보디아"},
{"cityCode":"PNH","city":"PHNOM PENH","country":"캄보디아"},
{"cityCode":"KZK","city":"KOMPONG THORN","country":"캄보디아"},
{"cityCode":"YMX","city":"MONTREAL MIRABEL","country":"캐나다"},
{"cityCode":"YQG","city":"WINDSOR LOCKS","country":"캐나다"},
{"cityCode":"YQX","city":"ST. THOMAS","country":"캐나다"},
{"cityCode":"YTO","city":"TORONTO","country":"캐나다"},
{"cityCode":"YUL","city":"MONTREAL","country":"캐나다"},
{"cityCode":"YVR","city":"VANCOUVER","country":"캐나다"},
{"cityCode":"YWG","city":"WINNIPEG","country":"캐나다"},
{"cityCode":"YXX","city":"EVOTHSFORD","country":"캐나다"},
{"cityCode":"YXY","city":"WHITEHORSE","country":"캐나다"},
{"cityCode":"YYC","city":"CALGARY","country":"캐나다"},
{"cityCode":"YYZ","city":"TORONTO","country":"캐나다"},
{"cityCode":"YZD","city":"DOWNSVIEW","country":"캐나다"},
{"cityCode":"YZF","city":"YELLOWKNIFE","country":"캐나다"},
{"cityCode":"YQB","city":"QUEBEC","country":"캐나다"},
{"cityCode":"YCN","city":"COCHRANE","country":"캐나다"},
{"cityCode":"YEG","city":"EDMONTON","country":"캐나다"},
{"cityCode":"YHZ","city":"HALIFAX","country":"캐나다"},
{"cityCode":"NBO","city":"NAIROBI","country":"케냐"},
{"cityCode":"ACD","city":"ACANDI","country":"콜롬비아"},
{"cityCode":"GUA","city":"GUATEMALA CITY","country":"콰테말라"},
{"cityCode":"KWI","city":"KUWAIT","country":"쿠웨이트"},
{"cityCode":"DBV","city":"DUBROVNIK","country":"크로아티아"},
{"cityCode":"PUY","city":"PULA","country":"크로아티아"},
{"cityCode":"BIE","city":"BISHKEK","country":"키르기즈스탄"},
{"cityCode":"LCA","city":"LARNACA","country":"키프로스"},
{"cityCode":"DAR","city":"DAR ES SALAAM","country":"탄자니아"},
{"cityCode":"BKK","city":"BANGKOK","country":"태국"},
{"cityCode":"BMK","city":"BANGKOK","country":"태국"},
{"cityCode":"CEI","city":"CHIANGMAI","country":"태국"},
{"cityCode":"CNX","city":"CHIANG MAI","country":"태국"},
{"cityCode":"CYI","city":"CHIAYI","country":"태국"},
{"cityCode":"DMK","city":"DON MUANG","country":"태국"},
{"cityCode":"URT","city":"SURAT TANN","country":"태국"},
{"cityCode":"UTP","city":"UTAPAO","country":"태국"},
{"cityCode":"NAK","city":"NAKHON RATCHASIMA","country":"태국"},
{"cityCode":"NBK","city":"SUVARNABHUMI","country":"태국"},
{"cityCode":"HKT","city":"PHUKET","country":"태국"},
{"cityCode":"KBV","city":"KRABI","country":"태국"},
{"cityCode":"ANK","city":"ANKARA","country":"터어키"},
{"cityCode":"AYT","city":"ANTALYA","country":"터어키"},
{"cityCode":"ASR","city":"KAYSERI","country":"터어키"},
{"cityCode":"SAW","city":"SABIHA GOKCEN","country":"터어키"},
{"cityCode":"UAB","city":"INCIRLIK","country":"터어키"},
{"cityCode":"USQ","city":"USAK","country":"터어키"},
{"cityCode":"ESB","city":"ANKARA ESENBOGA","country":"터어키"},
{"cityCode":"IST","city":"ISTANBUL","country":"터어키"},
{"cityCode":"ASB","city":"ASHKHABAD","country":"투르크매니스탄"},
{"cityCode":"CRZ","city":"CHARDZHEV","country":"투르크매니스탄"},
{"cityCode":"MYP","city":"MARY","country":"투르크매니스탄"},
{"cityCode":"DJE","city":"DJERBA","country":"튀니지"},
{"cityCode":"TUN","city":"TUNIS","country":"튀니지"},
{"cityCode":"PTY","city":"TOCUMEN INTERNATIONAL","country":"파나마"},
{"cityCode":"LHE","city":"LAHORE","country":"파키스탄"},
{"cityCode":"ISB","city":"ISLAMABAD","country":"파키스탄"},
{"cityCode":"KHI","city":"KARACHI","country":"파키스탄"},
{"cityCode":"POM","city":"PORTMORESBY","country":"파푸아뉴기니"},
{"cityCode":"LIM","city":"LIMA","country":"페루"},
{"cityCode":"LIS","city":"LISBON","country":"포르투갈"},
{"cityCode":"WAW","city":"WARSAW","country":"폴란드"},
{"cityCode":"WRO","city":"WROCLAW","country":"폴란드"},
{"cityCode":"CDG","city":"CHARLES DE GAULLE","country":"프랑스"},
{"cityCode":"CHR","city":"CHATEAUROUX","country":"프랑스"},
{"cityCode":"CMF","city":"CHAMBERY","country":"프랑스"},
{"cityCode":"TLS","city":"TOULOUSE","country":"프랑스"},
{"cityCode":"XCR","city":"CHALONS","country":"프랑스"},
{"cityCode":"MRS","city":"MARSEILLE PROVENCE","country":"프랑스"},
{"cityCode":"NCE","city":"NICE","country":"프랑스"},
{"cityCode":"ORY","city":"ORLY","country":"프랑스"},
{"cityCode":"PAR","city":"PARIS","country":"프랑스"},
{"cityCode":"PPT","city":"TAHITI","country":"프랑스"},
{"cityCode":"FNI","city":"NIMES","country":"프랑스"},
{"cityCode":"GNB","city":"GRENOBLE","country":"프랑스"},
{"cityCode":"LBG","city":"LE BOURGET","country":"프랑스"},
{"cityCode":"NAN","city":"NADI","country":"피지"},
{"cityCode":"HEL","city":"HELSINKI","country":"핀란드"},
{"cityCode":"CEB","city":"CEBU","country":"필리핀"},
{"cityCode":"CRK","city":"CLARKFIELD","country":"필리핀"},
{"cityCode":"DVO","city":"DAVAO","country":"필리핀"},
{"cityCode":"SFS","city":"SUBIC","country":"필리핀"},
{"cityCode":"LLU","city":"LAPULAPU","country":"필리핀"},
{"cityCode":"MDT","city":"MASBATE","country":"필리핀"},
{"cityCode":"MNL","city":"MANILA","country":"필리핀"},
{"cityCode":"NOP","city":"MCTAN","country":"필리핀"},
{"cityCode":"PPS","city":"PUERTO PRINCESA","country":"필리핀"},
{"cityCode":"KLO","city":"KALIBO","country":"필리핀"},
{"cityCode":"LAO","city":"LAOAG","country":"필리핀"},
{"cityCode":"CJJ","city":"CHEONGJU","country":"한국"},
{"cityCode":"CJU","city":"JEJU","country":"한국"},
{"cityCode":"YNY","city":"YANGYANG","country":"한국"},
{"cityCode":"UJN","city":"ULJIN","country":"한국"},
{"cityCode":"PUS","city":"BUSAN(GIMHAE)","country":"한국"},
{"cityCode":"RSU","city":"YOSU","country":"한국"},
{"cityCode":"SEL","city":"SEOUL","country":"한국"},
{"cityCode":"SHO","city":"SHOKCHO","country":"한국"},
{"cityCode":"SSN","city":"SUNGNAM","country":"한국"},
{"cityCode":"SUW","city":"SUWAEN","country":"한국"},
{"cityCode":"SWU","city":"SUWON","country":"한국"},
{"cityCode":"TAE","city":"DAEGU","country":"한국"},
{"cityCode":"TAN","city":"TAEAN","country":"한국"},
{"cityCode":"USN","city":"ULSAN","country":"한국"},
{"cityCode":"WJU","city":"WONJU","country":"한국"},
{"cityCode":"YEC","city":"YEICHON","country":"한국"},
{"cityCode":"MOK","city":"MOKPO","country":"한국"},
{"cityCode":"MPK","city":"MOKPO","country":"한국"},
{"cityCode":"MWX","city":"MUAN","country":"한국"},
{"cityCode":"OSN","city":"OSAN","country":"한국"},
{"cityCode":"GMP","city":"SEOUL(GIMPO)","country":"한국"},
{"cityCode":"HIN","city":"CHINJU","country":"한국"},
{"cityCode":"ICN","city":"INCHEON","country":"한국"},
{"cityCode":"JDG","city":"JEDONG","country":"한국"},
{"cityCode":"KAE","city":"KANGWEON","country":"한국"},
{"cityCode":"KAG","city":"KANG REUNG","country":"한국"},
{"cityCode":"KJG","city":"KOCHANG","country":"한국"},
{"cityCode":"KPE","city":"CHINHAE","country":"한국"},
{"cityCode":"KPO","city":"POHANG","country":"한국"},
{"cityCode":"KSG","city":"PYUNGTAEK","country":"한국"},
{"cityCode":"KSK","city":"SUSAK","country":"한국"},
{"cityCode":"KSM","city":"SINCHONRI","country":"한국"},
{"cityCode":"KSW","city":"SUWON","country":"한국"},
{"cityCode":"KTP","city":"HAEMI","country":"한국"},
{"cityCode":"KUV","city":"KUNSAN","country":"한국"},
{"cityCode":"KWJ","city":"GWANGJU","country":"한국"},
{"cityCode":"GDN","city":"GBANSK POIANB","country":"헝가리"},
{"cityCode":"ADL","city":"ADELAIDE","country":"호주"},
{"cityCode":"ASP","city":"ALICE SPRINGS","country":"호주"},
{"cityCode":"BNE","city":"BRISBANE","country":"호주"},
{"cityCode":"BWT","city":"BURNIE","country":"호주"},
{"cityCode":"CNS","city":"CAIRNS","country":"호주"},
{"cityCode":"DRW","city":"DARWIN","country":"호주"},
{"cityCode":"RAM","city":"RAMINGNING","country":"호주"},
{"cityCode":"ROK","city":"ROCKHAMPTON","country":"호주"},
{"cityCode":"SYD","city":"SYDNEY","country":"호주"},
{"cityCode":"MBB","city":"MEBANBECE","country":"호주"},
{"cityCode":"MEB","city":"MELBOURNE ESSENDON","country":"호주"},
{"cityCode":"MEL","city":"MELBOURNE","country":"호주"},
{"cityCode":"MRG","city":"MAREEBA","country":"호주"},
{"cityCode":"HKG","city":"HONG KONG","country":"홍콩"}]